### ISSUE TITLE
choiceModel.gaml and MoBalance.gaml broken

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#12]
Step to reproduce

Run choiceModel.gaml and MoBalance.gaml 
The model doesn't run anymore here the error thrown:

`````
2 occurrences in 2 agents at cycle 0: Java error: RuntimeException
in create zones from: geojson_zones with: [popsqmile::float(read('pop_per_sqmile')), zoneId::string(read('id'))];
RuntimeException: java.io.IOException: Error parsing urn:ogc:def:crs:OGC:1.3:CRS84 as crs id
org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.readNext(FeatureJSON.java:750)
org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.hasNext(FeatureJSON.java:734)
org.geotools.geojson.feature.FeatureJSON.readFeatureCollection(FeatureJSON.java:362)
msi.gama.util.file.GamaGeoJsonFile.getFeatureCollection(GamaGeoJsonFile.java:149)
msi.gama.util.file.GamaGeoJsonFile.readShapes(GamaGeoJsonFile.java:159)
msi.gama.util.file.GamaGeoJsonFile.fillBuffer(GamaGeoJsonFile.java:117)
msi.gama.util.file.GamaFile.getContents(GamaFile.java:346)
in agents Simulation 0, mobilityAI0
`````

Gama version 1.8 Offical Release

It migth come from the new version of GAMA. I will investigate this

**Comment by doorleyr** [comment]
I haven't been using this model for a while and the python scripts have changed quite a bit since then so there is probably an issue with the data produced by the python scripts.

The ABM we discussed (https://github.com/CityScope/CS_Mobility_Service/issues/13) would be significantly different from the existing one anyway. In the old ABM, I was doing the location and mode choices in GAMA but the idea now is to initiate agents from a cityIO json which already has their home/work locations and modes. It might be easiest to start from a new model for this. What do you think?

**Comment by agrignard** [comment]
I fixed it it was a simple bad projection naming convention in the file.

Regarding issue #13, it will be a very different model indeed however it's always good to have different and  a stand-alone model from GAMA working

If you think they are not relevant any more then it might be better to remove them or to archives them in a separated folder.
