### ISSUE TITLE
People in the river

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#5]
While running the model I just see that certain agent a crossing the charles river without taking the bridge.

I wander how it is possible if the agent are constrained on the road network.

<img width="569" alt="Screen Shot 2019-03-13 at 16 04 55" src="https://user-images.githubusercontent.com/3928502/54310918-e2e5a080-45a9-11e9-9e55-815ceec23624.png">

**Comment by RELNO** [comment]
https://www.youtube.com/watch?v=2y61BLmB9QE

**Comment by doorleyr** [comment]
I think it's because the agents select a destination as a random point within the appropriate census tract (which includes the river). This will get fixed when we transition to using the simulation on a smaller scale (using analytical approach for wider area) but we can still use this version for testing the bridges with cityIO.

**Comment by doorleyr** [comment]
Seems to be solved. May have been due to the sparsity of the road network in that initial version.
