### ISSUE TITLE
Apply the model to Hamburg Case Study

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#7]
We need to be able to deploy this model for Hamburg.

@doorleyr What is the datasets required to achieve this?
@RELNO can you point us to the Hamburg repo that might have some of this data?

**Comment by RELNO** [comment]
Thanks to Amy's work [UROP], a lot of Hamburg data sources are collected here: 

https://docs.google.com/document/d/1btBSp6qzZu5YP6sw7WZ3lpjUUJNqX628q3wkypElKBg/edit
https://docs.google.com/spreadsheets/d/1uoJpieOiL3uIUpGWJFJa6rWg-UFOWEGY7Lxf4K9Ftqs/edit#gid=0

**Comment by agrignard** [comment]
Amy mention some carto map in here doc
"I have generated a few maps on Carto, and the useful/interesting ones are linked above" 
Do we have access to them?

**Comment by RELNO** [comment]
It's in the links 'Hamburg land use and population data', 'Traffic accidents in Hamburg'

**Comment by agrignard** [comment]
Cool!
https://amyvogel.carto.com/builder/929ca889-b29c-43bf-998d-1bef7edc30b7/embed
https://amyvogel.carto.com/builder/6bde9de5-33a8-416d-8b9d-a0321e71a89d/embed

**Comment by doorleyr** [comment]
There's basically 2 categories of data we need: (i) individual data to calibrate behavioural models and (ii) aggregate data about the current demographics, O-D matrices etc.

As far as I can tell from my own research as well as Amy's, the [ German Mobility Panel](https://daten.clearingstelle-verkehr.de/order-form.html) data is the only suitable source of individual-level data. It costs €100.

- 
Amy found some aggregate demographic data but I haven't seen any source of data for O-D matrices which is the most important thing from my perspective.

In order to do a realistic simulation, we need to at least have the individual data and the O-D matrix at tract level (or similar). As a temporary solution, we could use the behavioural models from USA data but we still need an O-D matrix for Hamburg.

**Comment by RELNO** [comment]
@doorleyr we can arrange for a meeting with data team at HCU, they should either have or direct us to the source.
