### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#8]
1. Run the GAMA model in headless

2. See how this can be made by a server (I guess a python script?)

**Comment by RELNO** [comment]
The way we interact with SUMO is a python that runs the sumo binary and than collect the output, validates the output and send to cityIO. I used a multiprocess [async] approach so that cityIO `post` would not interfere with the simulation: https://github.com/CityScope/CS_CityScopeJS_Simulation/blob/master/CSjs_MAPBOX-GL-JS/sumo/grasbrook/traci_sumo.py

**Comment by doorleyr** [comment]
@agrignard it looks like you did some work on this in the cityIO_backend repo
https://github.com/CityScope/CS_CityIO_Backend/commit/87de86a15e84e4fd70a3907f6a938fe0e60d596f

To make this simulation headless, is it just a matter of adding a similar xml? How do you actually run it in headless mode?

**Comment by agrignard** [comment]
Yes I did (with the help of Patrick Taillandier and the GAMA team) a generic example in cityIO_backEnd that is reading and sending. As a proof of concept its possible to read/write table from GAMA. However there is still 2 bottlenecks to send simulation results through GAMA in headless (however it works fine with a GUI for now) (see https://github.com/gama-platform/gama/issues/2608) and more generally from any simulation software see https://github.com/CityScope/CS_CityIO_Backend/issues/67
